pull_request_rules:

  - name: trigger bors try when PR is created out
    conditions:
      - "-closed"
      - "-conflict"
      - author!=renovate[bot]
      - author!=iamsauravsharma
      - label!=["bors-trying-phase", "bors-staging-phase"]
      - "-merged"
      - status-success=WIP
    actions:
      comment:
        message: bors try
      label:
        add:
          - bors-trying-phase
  
  - name: merge renovate bot PR when approved review
    conditions:
      - approved-reviews-by=iamsauravsharma
      - author=renovate[bot]
      - label=["dependencies", "bors-trying-phase"]
      - status-success=Travis CI - Pull Request
    actions:
      comment:
        message: bors merge
      label:
        add:
          - bors-staging-phase
        remove:
          - bors-trying-phase


  - name: merge reviewed and status success PR
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - approved-reviews-by=iamsauravsharma
      - "-closed"
      - "-conflict"
      - label!=WIP
      - label="bors-trying-phase"
      - status-success=["DCO", "CommitCheck", "Travis CI - Pull Request", "WIP"]
    actions:
      comment:
        message: bors merge
      label:
        add:
          - bors-staging-phase
        remove:
          - bors-trying-phase

  - name: merge status success iamsauravsharma PR
    conditions:
      - author=iamsauravsharma
      - "-closed"
      - "-conflict"
      - label!=WIP
      - status-success=["DCO", "CommitCheck", "Travis CI - Pull Request", "WIP"]
    actions:
      comment:
        message: bors merge
      label:
        add:
          - bors-staging-phase
  
  - name: auto close invalid or duplicate PR
    conditions:
      - "-closed"
      - label~=^(invalid|duplicate)$
    actions:
      close:
        message: |
          This PR is automatically closed by Mergify. This PR was labeled as invalid or duplicate by collaborators
      label:
        remove:
          - bors-trying-phase
  
  - name: remove label from merged PR
    conditions:
      - merged
      - label=bors-staging-phase
    actions:
      label:
        remove:
         - bors-staging-phase