language: rust

rust:
  - stable
  - beta
  - nightly

git:
  depth: false
 
dist: xenial
  
os:
  - linux
  - osx
  - windows

install:
  - rustup component add rustfmt && RUSTFMT="yes" || RUSTFMT="no"
  - rustup component add clippy && CLIPPY="yes" || CLIPPY="no"

before_script:
  - if [[ "$RUSTFMT" == "yes" ]]; then
      rustfmt -V;
    fi
  - if [[ "$CLIPPY" == "yes" ]]; then
      cargo clippy -V;
    fi

script:
  - if [[ "$RUSTFMT" == "yes" ]]; then
      cargo fmt --all -- --check;
    fi
  - if [[ "$CLIPPY" == "yes" ]]; then
      cargo clippy --all -- -D warnings;
    fi
  - cargo build --all
  - cargo doc --no-deps --all
  - cargo test --all

after_script:
  - cargo install --path .
  - bash scripts/install_crate.sh
  - cargo trim -s $TRAVIS_BUILD_DIR/..
  - bash scripts/cargo_trim_command_test.sh