language: rust

git:
  depth: false
 
dist: xenial

jobs:
  include:
  - os: linux
    env: PUBLISH_PACKAGE=true
  - os: osx
  - os: windows
  - rust: beta
  - rust: nightly
  - os: linux
    env: TARGET=x86_64-unknown-linux-musladdons:
    apt:
      update: true
      packages: musl-tools
  - os: windows
    env: TARGET=x86_64-pc-windows-msvc

branches:
  only:
    - staging
    - trying
    - master
    - /^v\d+\.\d+\.\d+(-\S*)?$/

before_install:
- chmod -R 777 ci

install:
- . ci/install.sh

before_script:
- . ci/before_script.sh

script:
- . ci/script.sh

deploy:
  provider: cargo
  token: $CARGO_TOKEN
  on:
    tags: true
    condition: $PUBLISH_PACKAGE = true

notifications:
  email: false