[package]
name = "cargo-trim"
version = "0.5.3"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
homepage = "https://github.com/iamsauravsharma/cargo-trim"
repository = "https://github.com/iamsauravsharma/cargo-trim"
description = "Binary application to cleanup $CARGO_HOME cache"
license = "MIT"
readme = "README.MD"
edition = "2018"
keywords = ["cargo","cache","remove","manage","clean"]
categories = ["command-line-utilities"]

[dependencies]
clap = "2.33.0"
colored = "1.9.2"
dirs = "2.0.2"
fs_extra = "1.1.0"
pretty-bytes = "0.2.2"
semver = "0.9.0"
serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0.48"
toml = "0.5.6"

[dev-dependencies]
pretty_assertions = "0.6.1"

[features]
no-color = ["colored/no-color"]